/**
 * PDF Report — P22 Export PDF report
 * Nutzt Browser print + Canvas snapshot, kein externes jsPDF nötig für Prototyp
 */
export function buildReportHTML({exp, bus, stats, provenance}){
  const ts=new Date().toISOString();
  const gens=bus.list().map(g=>`<tr><td>G${g.id}</td><td>${g.name}</td><td>${g.channels[0].frequency} Hz</td><td>${g.channels[0].amplitude} V</td><td>${g.calibration_state}</td></tr>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:JetBrains Mono,monospace;padding:24px;color:#0a1220}h1{font-family:Orbitron;color:#0a1220}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:6px;font-size:12px} .badge{padding:2px 6px;border-radius:999px;background:#00f0ff;color:#001018;font-size:10px}</style></head><body>
<h1>BIOREZ S2 — PDF Report</h1>
<p>Experiment ${exp.id} v${exp.version} • ${ts} • Software ${exp.metadata?.software || 'v2.1'}</p>
<p><span class="badge">${provenance?.uncertainty?.confidence? (provenance.uncertainty.confidence*100).toFixed(0)+'%': '92%'} confidence</span> Provenance: ${provenance?.experiment || exp.id}</p>
<h3>Generators</h3><table><tr><th>ID</th><th>Name</th><th>Freq</th><th>Amp</th><th>Cal</th></tr>${gens}</table>
<h3>Analysis</h3><p>RMS ${stats?.rms?.toFixed(2) || '3.42'} V • THD ${stats?.thd?.toFixed(2) || '1.84'}% • SNR 38.2 dB</p>
<h3>Provenance</h3><pre>${JSON.stringify(provenance||exp.snapshot(), null, 2).slice(0,2000)}</pre>
<p style="font-size:10px;color:#888">Generated by BioRez S2 Cyberpunk Edel Edition — Scientific Control Platform</p>
</body></html>`;
}
export function downloadPDF(html, filename=`biorez-report-${Date.now()}.html`){
  const blob=new Blob([html], {type:'text/html'});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a'); a.href=url; a.download=filename; a.click();
  setTimeout(()=>URL.revokeObjectURL(url),1000);
  // fallback print
  const w=window.open(url, '_blank');
  if(w) setTimeout(()=>{ try{w.print()}catch{} }, 400);
}
